---
title: Profi Földmunka
author: Peti
email: info@profifoldmunka.hu
description: Profi Földmunka
baseurl: "/somfarm"
url: https://vestalux.github.io
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
